# Generated by Django 3.0.3 on 2020-02-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
    ]
