# Generated by Django 3.0.3 on 2020-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_abc_to_mti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
